### ISSUE TITLE
Raise an exception instead of returning null if  the qrImageScanner is not set

### ISSUE THREAD

**Issue by jeremi** [idpass/idpass-lite-java#17]
https://github.com/idpass/idpass-lite-java/blob/79201a6a49c04d7288c7eef09013e8defeabcdd9/src/main/java/org/idpass/lite/IDPassReader.java#L262

https://github.com/idpass/idpass-lite-java/blob/79201a6a49c04d7288c7eef09013e8defeabcdd9/src/main/java/org/idpass/lite/IDPassReader.java#L276

**Comment by typelogic** [comment]
Fixed in https://github.com/idpass/idpass-lite-java/commit/4f23f4ae578f06c8861118e21fbc78ebd262a459
